In [1]:
pip install numpy



[notice] A new release of pip available: 22.1.2 -> 22.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np

In [ ]:
# 1 task

In [9]:
a = np.matrix("0.05,0.07,0;0.05,0,0.06;1,1,1")
b = np.matrix("2250;1400;50000")
a_solve = np.linalg.solve(a,b)
a_solve

matrix([[10000.],
        [25000.],
        [15000.]])

In [5]:
# 2 task

In [20]:
a = np.matrix("0,2,1;2,1,0;1,1,1")
b = np.matrix("1448;1428;1328")
a_solve = np.linalg.solve(a,b)
result = a_solve.astype('int')
result

matrix([[436],
        [556],
        [336]])

In [10]:
# 3 task

In [2]:
a = np.matrix("3,0,3;6,0.25,0;1,0.33,1")
b = np.matrix("1;1;1")
a_solve = np.linalg.solve(a,b)
a_solve

matrix([[0.08249158],
        [2.02020202],
        [0.25084175]])

In [4]:
a = round(a_solve[0, 0], 1)
b = round(a_solve[1, 0], 1)
c = round(a_solve[2, 0], 1)
a, b ,c

(0.1, 2.0, 0.3)

In [5]:
def get_result(n):
    result = 1 / n
    result = round(result, 1)
    return result

In [10]:
a = get_result(a)
b = get_result(b)
c = get_result(c)
a, b, c

(10.0, 0.5, 3.3)

In [11]:
# 4 task

In [18]:
a = np.matrix("1,1,1;9,3,1;1,-1,1")
b = np.matrix("12;54;2")
a_solve = np.linalg.solve(a,b)
result = a_solve.astype('int')
result

matrix([[4],
        [5],
        [3]])

In [19]:
# 5 task

In [32]:
from numpy import array
def get_polynom(coords: list) -> array:
    a = []
    b = []
    for x, y in coords:
        row = []
        b.append(y)
        for i in range(len(coords)):
            row.append(x ** i)
        a.append(row)
    return np.linalg.solve(a, b).astype('int')


print(get_polynom([(1,2), (3,4)]))

[1 1]
